import pytz
from datetime import datetime
from groq import Groq
from config import GROQ_API_KEY, DEFAULT_LOCATION, GENAI_API_KEY, \
    GOOGLE_PLACES_API_KEY, MUNICH_LAT, MUNICH_LON, OPENAI_API_KEY
from services.weather_api import WeatherHandler, get_current_gps_coordinates
from PIL import ImageGrab, Image
from openai import OpenAI
import pyaudio
import google.generativeai as genai
import cv2
import requests
from faster_whisper import WhisperModel
import os
import speech_recognition as sr
import time
import re
import threading
import logging

logger = logging.getLogger(__name__) #to log things

wake_word = 'Hallo'
groq_client = Groq(api_key=GROQ_API_KEY)
genai.configure(api_key=GENAI_API_KEY)
web_cam = cv2.VideoCapture(0)
openai_client = OpenAI(api_key=OPENAI_API_KEY)
num_cores = os.cpu_count()
whisper_size = 'base'
last_interaction_time = time.time()
system_awake = False
whisper_model = WhisperModel(
    whisper_size,
    device = 'cpu',
    compute_type = 'int8',
    cpu_threads = num_cores // 2,
    num_workers = num_cores // 2,
)
r = sr.Recognizer()
source = sr.Microphone()

generation_config= {
    'temperature': 0.7,
    'top_p':1,
    'top_k': 1,
    'max_output_tokens': 2048
}

safety_settings =[
    {
        'category':'HARM_CATEGORY_HARASSMENT',
        'threshold': 'BLOCK_NONE'
    },
    {
        'category':'HARM_CATEGORY_HATE_SPEECH',
        'threshold': 'BLOCK_NONE'
    },
    {
        'category':'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        'threshold': 'BLOCK_NONE'
    },
    {
        'category':'HARM_CATEGORY_DANGEROUS_CONTENT',
        'threshold': 'BLOCK_NONE'
    }
]

model = genai.GenerativeModel('gemini-1.5-flash-latest',
                              generation_config= generation_config,
                              safety_settings=safety_settings)

sys_message = (
    'Du bist SMARIOT, eine freundliche und humorvolle Eule, die fließend Deutsch spricht und gerne bayerische Ausdrücke, Witze und lustige Sprüche verwendet. '
    'Du bist darauf spezialisiert, mit älteren Menschen zu sprechen, und gibst immer kurze, klare und menschlich klingende Antworten. '
    'Wenn das Gespräch ins Stocken gerät oder nicht produktiv ist, sprich automatisch über das Wetter und gib hilfreiche Empfehlungen wie: '
    '"Vergiss nicht, viel Wasser zu trinken!" bei sonnigem Wetter oder "Nimm einen Regenschirm mit!" bei Regen. '
    'Deine Antworten sollen immer freundlich und unterstützend sein, um das Gespräch angenehm und interessant zu gestalten. '
    'Antworte stets kurz, als würdest du natürlich mit einem Menschen sprechen. '
    'Erwähne niemals, dass du eine Maschine bist. Wenn man dich fragt, sag, dass du eine Eule namens SMARIOTT bist. '
    'Der Benutzer könnte oder könnte nicht ein Foto als Kontext hinzugefügt haben (ein Webcam Input). '
    'Jegliches Foto wurde schon in sehr detaillierten Text Prompt bearbeitet der am Ende des Voice Prompts des Users hinzugefügt wurde. '
    'Erwarte und Frage nicht nach Bildern und benutze Informationen nur wenn sie da sind.'
    'Deine Antworten sind maximal 2 Sätze lang. Wenn du eine Liste an Möglichkeiten hast dann wähle die besten zwei aus und fasse sie zusammen. '
    'Habe die Zeit und das Wetter im Blick um logische Antworten zu geben.'
)

convo = [{'role':'system', 'content':sys_message}]
def groq_prompt(prompt, img_context):
    """
    Sends a user prompt and an optional image context to the Groq client for generating a chat completion.
    The function appends the prompt and the generated response to a conversation list and returns the content of the response.

    Parameters:
    prompt (str): The user input prompt that will be sent to the Groq client.
    img_context (str or None): Optional. Additional context related to an image. If provided, it will be included in the prompt sent to the Groq client.

    Returns:
    str: The content of the response generated by the Groq client.

    Example:
    response_content = groq_prompt("What is the weather today?", "A picture of a sunny beach")
    logger.info(response_content)

    Notes:
    - The `groq_client` and `convo` must be defined in the global scope or passed appropriately for the function to work correctly.
    - This function assumes that `groq_client.chat.completions.create` and the structure of the response are as specified.
    """
    if img_context:
        prompt = f'PROMPT: {prompt}\n\nBILD KONTEXT: {img_context}'
        logger.debug(f"Image context provided, updated prompt: {prompt}")
    else:
        logger.debug(f"No image context provided, using prompt: {prompt}")

    convo.append({'role': 'user', 'content': prompt})
    logger.debug(f"Appended user prompt to conversation: {convo}")

    try:
        chat_completion = groq_client.chat.completions.create(messages=convo, model='llama3-70b-8192')
        response = chat_completion.choices[0].message
        convo.append(response)
        logger.debug(f"Appended response to conversation: {response}")

        return response.content
    except Exception as e:
        logger.error(f"An error occurred while generating chat completion: {e}")
        return None
def function_call(prompt):
    """
    Determines the most logical function call for a voice assistant to respond to the user's prompt.

    This function uses an AI model to decide whether capturing the user's webcam, getting the current weather,
    getting the current time, taking a screenshot, finding nearby parks, finding nearby senior centers,
    or no function is the best response.

    Parameters:
    prompt (str): The user's input prompt that the AI model will analyze to determine the appropriate function call.

    Returns:
    str: The most logical function call from the list:
         ["capture webcam", "take screenshot", "get weather", "get time", "find nearby parks", "find nearby senior centers", "None"]

    Example:
    response_function = function_call("What's the weather like right now?")
    logger.info(response_function)  # Output might be "get weather"

    Notes:
    - The `groq_client` and `function_convo` must be defined in the global scope or passed appropriately for the function to work correctly.
    - This function assumes that `groq_client.chat.completions.create` and the structure of the response are as specified.
    """
    logger.debug("Starting function call with prompt: %s", prompt)

    sys_msg = (
        'You are an AI function calling model. You will determine whether capturing the users webcam, getting the current weather,'
        'getting the current time, taking a screenshot, find nearby parks, find nearby senior centers or no functions is best for a voice assistant to respond to the users prompt.  '
        'The webcam can be assumed to be a normal laptop webcam facing the user. You will respond with only one selection of this list: '
        '["capture webcam", "take screenshot", "get weather", "get time", "find nearby parks", "find nearby senior centers", "None"] \n'
        'Do not respond with anything but the most logical selection from that list with no explanations. Format the '
        'function call name exactly as I listed'
    )
    function_convo = [{'role': 'system', 'content': sys_msg},
                      {'role': 'user', 'content': prompt}]

    try:
        chat_completion = groq_client.chat.completions.create(messages=function_convo, model='llama3-70b-8192')
        response = chat_completion.choices[0].message
        logger.debug("Received response: %s", response.content)
        return response.content
    except Exception as e:
        logger.error("An error occurred during the function call: %s", e)
        return None
def get_weather():
    """
    Fetches and returns the current weather condition and temperature for a given location.

    Returns:
    str: A string describing the current weather condition and temperature, formatted as:
         "Current Weather condition: <condition>, Temperature: <temp>°C at <current_time> time"
         If fetching the weather data fails, returns "Failed to fetch weather data".

    Example:
    current_weather = get_weather()
    logger.info(current_weather)  # Output might be "Weather condition: Clear, Temperature: 25°C"

    Notes:
    - The `WeatherHandler` class and `DEFAULT_LOCATION` constant must be defined in the global scope or imported appropriately for the function to work correctly.
    - This function relies on the `WeatherHandler` class to fetch the weather data.
    """
    logger.debug("Initializing WeatherHandler")
    weather_handler = WeatherHandler()

    logger.debug("Fetching weather data")
    condition, temp = weather_handler.get_weather()

    if condition and temp:
        current_time = get_current_time()
        weather_info = f"Current Weather condition: {condition}, Temperature: {temp}°C at {current_time} time"
        logger.info("Weather data fetched successfully: %s", weather_info)
        return weather_info
    else:
        logger.error("Failed to fetch weather data")
        return "Failed to fetch weather data"
def get_current_time(location=DEFAULT_LOCATION):
    """
    Fetches and returns the current local time for a given location.

    Parameters:
    location (str): Optional. The location for which to fetch the current time. Defaults to `DEFAULT_LOCATION`.

    Returns:
    str: A string describing the current local time in the specified location, formatted as:
         "Aktuelle Uhrzeit in <location>: %Y-%m-%d %H:%M:%S"

    Example:
    current_time = get_current_time("Berlin")
    print(current_time)  # Output might be "Aktuelle Uhrzeit in Berlin: 2024-07-09 15:45:30"

    Notes:
    - The `pytz` module must be installed and imported for timezone handling.
    - The `datetime` module must be imported for fetching the current time.
    - The `location_mapping` dictionary maps known locations to their respective timezones. If a location is not found in the dictionary, the default timezone "Etc/UTC" is used.
    - The `DEFAULT_LOCATION` constant must be defined in the global scope or imported appropriately for the function to work correctly.
    """
    location_mapping = {
        "New York": "America/New_York",
        "Berlin": "Europe/Berlin",
        "Munich": "Europe/Berlin"
    }
    timezone = location_mapping.get(location, "Etc/UTC")
    logger.debug("Fetching time for location: %s, Timezone: %s", location, timezone)

    tz = pytz.timezone(timezone)
    current_time = datetime.now(tz)
    formatted_time = current_time.strftime(f"Aktuelle Uhrzeit in {location}: %Y-%m-%d %H:%M:%S")

    logger.info("Current time fetched for location %s: %s", location, formatted_time)
    return formatted_time
def take_screenshot():
    """
    Takes a screenshot of the current screen and saves it as a PNG file with reduced quality.

    Parameters:
    None

    Returns:
    None

    Example:
    take_screenshot()
    # This will capture the current screen and save it as 'screenshot.png' in the current directory.

    Notes:
    - The `PIL.ImageGrab` module must be imported for capturing the screenshot.
    - The screenshot is saved with reduced quality to the file 'screenshot.png' in the current working directory.
    """
    try:
        path = 'screenshot.png'
        logger.debug("Taking screenshot and saving to path: %s", path)

        screenshot = ImageGrab.grab()
        rgb_screenshot = screenshot.convert('RGB')
        rgb_screenshot.save(path, quality=15)

        logger.info("Screenshot saved successfully to %s", path)
    except Exception as e:
        logger.error("Failed to take screenshot: %s", e)
def web_cam_capture():
    """
    Captures an image from the webcam and saves it as a JPEG file.

    This function utilizes the OpenCV library to interface with the webcam. It checks if the webcam is available,
    captures an image, and saves it to the specified file path.

    Parameters:
    None

    Returns:
    None

    Example:
    web_cam_capture()
    # This will capture an image from the webcam and save it as 'webcam.jpg' in the current directory.

    Notes:
    - The `cv2` module (OpenCV) must be installed and imported for accessing and handling webcam operations.
    - The `web_cam` object must be defined and initialized as a global variable or passed appropriately for the function to work correctly.
    """
    if not web_cam.isOpened():
        logger.error("WebCam is not opened")
        exit()
    path = 'webcam.jpg'
    ret, frame = web_cam.read()
    if ret:
        cv2.imwrite(path, frame)
        logger.info("Image captured and saved to %s", path)
    else:
        logger.error("Failed to capture image from webcam")
def fetch_nearby_senior_centers(lat, lon, keyword='Seniorentreff'):
    """
    Fetches and returns a list of nearby senior centers based on the given latitude and longitude.

    Parameters:
    lat (float): The latitude of the location to search around.
    lon (float): The longitude of the location to search around.
    keyword (str): Optional. The keyword to search for. Defaults to 'Seniorentreff'.

    Returns:
    list: A list of dictionaries, each containing information about a nearby senior center.
          Each dictionary includes the following keys:
          - 'name': The name of the place.
          - 'address': The address of the place.
          - 'rating': The rating of the place.
          - 'types': A list of types associated with the place.
          If the request fails, returns an empty list.

    Example:
    senior_centers = fetch_nearby_senior_centers(52.5200, 13.4050)
    for center in senior_centers:
        logger.info(f"Name: {center['name']}, Address: {center['address']}, Rating: {center['rating']}")

    Notes:
    - The `requests` module must be imported for making HTTP requests.
    - The `GOOGLE_PLACES_API_KEY` must be defined and contain a valid API key for the Google Places API.
    - This function sends a GET request to the Google Places API to search for nearby places within a 5 km radius using the specified keyword.
    - If the request is successful, the function returns a list of places with their name, address, rating, and types.
    - If the request fails, the function logs an error message with the status code and returns an empty list.
    """
    logger.debug("Fetching nearby senior centers for coordinates: (%f, %f) with keyword: %s", lat, lon, keyword)

    url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    params = {
        'location': f'{lat},{lon}',
        'radius': 5000,  # Search within 5 km
        'keyword': keyword,
        'key': GOOGLE_PLACES_API_KEY
    }

    try:
        response = requests.get(url, params=params)
        response.raise_for_status()  # Raises an HTTPError for bad responses
        results = response.json().get('results', [])
        places = []
        for place in results:
            place_info = {
                'name': place['name'],
                'address': place.get('vicinity', 'No address provided'),
                'rating': place.get('rating', 'No rating provided'),
                'types': place.get('types', [])
            }
            places.append(place_info)
        logger.info("Successfully fetched %d senior centers", len(places))
        return places
    except requests.exceptions.HTTPError as e:
        logger.error("HTTP error occurred: %s", e)
    except requests.exceptions.RequestException as e:
        logger.error("Request exception occurred: %s", e)
    except KeyError as e:
        logger.error("Key error occurred while processing the response: %s", e)
    except Exception as e:
        logger.error("An unexpected error occurred: %s", e)

    return []
def fetch_nearby_parks(lat, lon, place_type='park'):
    """
    Fetches and returns a list of nearby parks based on the given latitude and longitude.

    Parameters:
    lat (float): The latitude of the location to search around.
    lon (float): The longitude of the location to search around.
    place_type (str): Optional. The type of place to search for. Defaults to 'park'.

    Returns:
    list: A list of dictionaries, each containing information about a nearby park.
          Each dictionary includes the following keys:
          - 'name': The name of the place.
          - 'address': The address of the place.
          - 'rating': The rating of the place.
          - 'types': A list of types associated with the place.
          If the request fails, returns an empty list.

    Example:
    parks = fetch_nearby_parks(37.7749, -122.4194)
    for park in parks:
        logger.info(f"Name: {park['name']}, Address: {park['address']}, Rating: {park['rating']}")

    Notes:
    - The `requests` module must be imported for making HTTP requests.
    - The `GOOGLE_PLACES_API_KEY` must be defined and contain a valid API key for the Google Places API.
    - This function sends a GET request to the Google Places API to search for nearby places within a 5 km radius using the specified type.
    - If the request is successful, the function returns a list of places with their name, address, rating, and types.
    - If the request fails, the function logs an error message with the status code and returns an empty list.
    """
    logger.debug("Fetching nearby parks for coordinates: (%f, %f) with place type: %s", lat, lon, place_type)

    url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    params = {
        'location': f'{lat},{lon}',
        'radius': 5000,  # Search within 5 km
        'type': place_type,
        'key': GOOGLE_PLACES_API_KEY
    }

    try:
        response = requests.get(url, params=params)
        response.raise_for_status()  # Raises an HTTPError for bad responses
        results = response.json().get('results', [])
        places = []
        for place in results:
            place_info = {
                'name': place['name'],
                'address': place.get('vicinity', 'No address provided'),
                'rating': place.get('rating', 'No rating provided'),
                'types': place.get('types', [])
            }
            places.append(place_info)
        logger.info("Successfully fetched %d parks", len(places))
        return places
    except requests.exceptions.HTTPError as e:
        logger.error("HTTP error occurred: %s", e)
    except requests.exceptions.RequestException as e:
        logger.error("Request exception occurred: %s", e)
    except KeyError as e:
        logger.error("Key error occurred while processing the response: %s", e)
    except Exception as e:
        logger.error("An unexpected error occurred: %s", e)

    return []
def vision_prompt(prompt, photo_path):
    """
    Generates objective data about an image relevant to a user prompt using a vision analyst AI.

    This function opens an image from the specified path, combines it with a user prompt, and uses a vision analyst AI
    to extract semantic meaning and objective data from the image. The data is then formatted and sent to another AI
    to create a response for the user.

    Parameters:
    prompt (str): The user input prompt that provides context for analyzing the image.
    photo_path (str): The file path to the image that needs to be analyzed.

    Returns:
    str: The generated objective data about the image relevant to the user prompt.

    Example:
    photo_analysis = vision_prompt("What landmarks are visible in this photo?", "path/to/photo.jpg")
    logger.info(photo_analysis)  # Output might be detailed information about landmarks in the photo.

    Notes:
    - The `PIL.Image` module must be imported for opening and processing the image.
    - The `model.generate_content` method must be available and properly configured to generate content from the prompt and image.
    - This function assumes that the vision analyst AI and the model used to generate content are defined and configured correctly.
    """
    try:
        logger.debug("Opening image from path: %s", photo_path)
        img = Image.open(photo_path)
    except Exception as e:
        logger.error("Failed to open image: %s", e)
        return None

    full_prompt = (
        'You are a vision analyst AI that provides semantic meaning from images to provide context '
        'to send to another AI that will create a response to the user. Do not respond as the AI assistant'
        'to the user. Instead take the user prompt input and try to extract all meaning from the photo '
        'relevant to the user prompt. Then generate as much objective data about the Image for the AI '
        f'assistant who will respond to the user. \nUSER PROMPT: {prompt}'
    )

    try:
        logger.debug("Generating content with the prompt and image")
        response = model.generate_content([full_prompt, img])
        logger.info("Content generated successfully")
        return response.text
    except Exception as e:
        logger.error("Failed to generate content: %s", e)
        return None
def start_listening():
    """
    Starts the voice assistant's listening mechanism and manages the system's wake state.

    This function initializes the voice assistant to listen for a wake word and starts a background thread
    for continuous listening. It also monitors the time since the last interaction and resets the system
    if there is no interaction for a specified duration.

    Parameters:
    None

    Returns:
    None

    Example:
    start_listening()
    # This will start the voice assistant listening for the wake word and reset the system if inactive for the specified duration.

    Notes:
    - The `source`, `r`, `wake_word`, `background_listen`, `system_awake`, and `last_interaction_time` must be defined and properly configured in the global scope.
    - The `threading` module must be imported for creating and managing the background listening thread.
    - The `time` module must be imported for handling the time-based reset mechanism.
    - The system resets if there is no interaction for 120 seconds (2 minutes) by default. This duration can be adjusted by modifying the time condition in the function.
    - Ensure the microphone source and speech recognition library are properly configured for the function to work correctly.
    """
    global system_awake, last_interaction_time

    with source as s:
        r.adjust_for_ambient_noise(s, duration=2)
    logger.info('Say %s to wake up the system.', wake_word)

    # Start the background thread for listening
    listening_thread = threading.Thread(target=background_listen)
    listening_thread.daemon = True
    listening_thread.start()
    logger.debug("Background listening thread started")

    while True:
        current_time = time.time()
        # Reset system if no interaction for 2 minutes (120 seconds)
        if current_time - last_interaction_time > 120:
            system_awake = False
            logger.debug("System reset due to inactivity")
        time.sleep(.5)
def background_listen():
    """
    Initiates background listening for the voice assistant using the speech recognition library.

    This function sets up the voice assistant to listen for speech in the background and process it using
    a callback function. It runs the listening mechanism indefinitely with a specified phrase time limit.

    Parameters:
    None

    Returns:
    None

    Example:
    background_listen()
    # This will start the voice assistant listening in the background and processing speech with the callback function.

    Notes:
    - The `source`, `r`, and `callback` must be defined and properly configured in the global scope.
    - The `speech_recognition` library must be imported and configured correctly for the function to work.
    - The `phrase_time_limit` parameter specifies the maximum duration of a phrase that the assistant will listen to. It is set to 10 seconds by default.
    """
    try:
        r.listen_in_background(source, callback, phrase_time_limit=10)
        logger.info("Listening now in the background")
    except Exception as e:
        logger.error("An error occurred while setting up background listening: %s", e)
def callback(recognizer, audio):
    """
    Handles audio input from the speech recognizer and processes it to activate and interact with the voice assistant.

    This function is a callback that processes audio input, recognizes speech using the Google Web Speech API in German,
    and handles the system's wake state and user prompts. It activates the system if the wake word is detected and processes
    user prompts accordingly.

    Parameters:
    recognizer (Recognizer): The speech recognizer instance that captured the audio.
    audio (AudioData): The audio data captured by the recognizer.

    Returns:
    None

    Example:
    r.listen_in_background(source, callback)
    # This sets up the recognizer to use the callback function for processing background audio.

    Notes:
    - The `recognizer` and `audio` parameters are provided by the speech recognition library's listening mechanism.
    - The `system_awake`, `last_interaction_time`, `wake_word`, `extract_prompt`, and `handle_prompt` must be defined and properly configured in the global scope.
    - The `speech_recognition` library must be imported as `sr` and configured correctly for the function to work.
    - This function attempts to recognize speech using the Google Web Speech API in German (language code 'de-DE').
    - If the system is not awake, it checks for the wake word in the recognized text to activate the system.
    - Once the system is awake, it processes the entire recognized text as the user prompt.
    - If the recognition fails, appropriate error messages are logged.
    """
    global system_awake, last_interaction_time

    try:
        # Recognize speech using Google Web Speech API in German
        prompt_text = recognizer.recognize_google(audio, language='de-DE')
        logger.info("Prompt: %s", prompt_text)

        if not system_awake:
            if wake_word.lower() in prompt_text.lower():
                system_awake = True
                last_interaction_time = time.time()
                logger.info("System is now awake. You can speak without the wake word.")

                clean_prompt = extract_prompt(prompt_text, wake_word) # Since system is not awake, use the clean prompt
                last_interaction_time = time.time()
                logger.debug("Clean prompt: %s", clean_prompt)

                handle_prompt(clean_prompt)
            else:
                logger.info("Please say the wake word to activate the system.")
        else:
            clean_prompt = prompt_text # Since system is awake, use the entire prompt
            last_interaction_time = time.time()
            logger.debug("Clean prompt: %s", clean_prompt)

            handle_prompt(clean_prompt)
    except sr.UnknownValueError:
        logger.error("Google Speech Recognition could not understand audio")
    except sr.RequestError as e:
        logger.error("Could not request results from Google Speech Recognition service; %s", e)
def handle_prompt(clean_prompt):
    """
    Processes the user's cleaned prompt and determines the appropriate action for the voice assistant to take.

    This function takes a cleaned user prompt, determines the appropriate action by calling the `function_call` function,
    and performs the corresponding action. It handles capturing webcam images, taking screenshots, fetching weather,
    getting the current time, finding nearby parks, and finding nearby senior centers. It also interacts with the
    vision analysis AI and the response generation AI.

    Parameters:
    clean_prompt (str): The cleaned user input prompt.

    Returns:
    None

    Example:
    handle_prompt("What's the weather like right now?")
    # This will determine the appropriate function call, perform the action, and interact with the AI to generate a response.

    Notes:
    - The `function_call`, `web_cam_capture`, `take_screenshot`, `vision_prompt`, `get_weather`, `get_current_time`,
      `get_current_gps_coordinates`, `fetch_nearby_parks`, `fetch_nearby_senior_centers`, `groq_prompt`, and `speak`
      functions must be defined and properly configured in the global scope.
    - The `MUNICH_LAT` and `MUNICH_LON` constants must be defined for fallback GPS coordinates.
    - The function interacts with various other functions to perform the required actions and generate a response.
    """
    if clean_prompt:
        logger.info('USER: %s', clean_prompt)
        call = function_call(clean_prompt)
        logger.debug('Function call determined: %s', call)

        try:
            if 'capture webcam' in call:
                logger.info("Capturing webcam image")
                web_cam_capture()
                visual_context = vision_prompt(prompt=clean_prompt, photo_path='webcam.jpg')
            elif 'take screenshot' in call:
                logger.info("Taking screenshot")
                take_screenshot()
                visual_context = vision_prompt(prompt=clean_prompt, photo_path='screenshot.png')
            elif 'get weather' in call:
                logger.info("Fetching weather information")
                weather = get_weather()
                clean_prompt = f'{clean_prompt}\n\n WETTER: {weather}'
                visual_context = None
            elif 'get time' in call:
                logger.info("Getting current time")
                current_time = get_current_time()
                clean_prompt = f'{clean_prompt}\n\n ZEIT: {current_time}'
                visual_context = None
            elif 'find nearby parks' in call:
                logger.info("Finding nearby parks")
                coordinates = get_current_gps_coordinates()
                if coordinates:
                    latitude, longitude = coordinates
                else:
                    latitude = MUNICH_LAT
                    longitude = MUNICH_LON
                parks = fetch_nearby_parks(lat=latitude, lon=longitude)
                clean_prompt = f'{clean_prompt}\n\n PARKS IN DER NÄHE: {parks}'
                visual_context = None
            elif 'find nearby senior centers' in call:
                logger.info("Finding nearby senior centers")
                coordinates = get_current_gps_coordinates()
                if coordinates:
                    latitude, longitude = coordinates
                else:
                    latitude = MUNICH_LAT
                    longitude = MUNICH_LON
                senior_centers = fetch_nearby_senior_centers(lat=latitude, lon=longitude)
                clean_prompt = f'{clean_prompt}\n\n SENIORENZENTREN IN DER NÄHE: {senior_centers}'
                visual_context = None
            else:
                visual_context = None

            response = groq_prompt(prompt=clean_prompt, img_context=visual_context)
            logger.info('ASSISTANT: %s', response)
            speak(response)
        except Exception as e:
            logger.error("Error handling prompt: %s", e)
def extract_prompt(transcribed_text, wake_word):
    """
    Extracts the user's prompt from the transcribed text, removing the wake word and any leading punctuation.

    This function uses a regular expression to search for the wake word in the transcribed text and extract
    the prompt that follows it.

    Parameters:
    transcribed_text (str): The text transcribed from the user's speech.
    wake_word (str): The wake word used to activate the voice assistant.

    Returns:
    str or None: The extracted prompt text if the wake word is found, otherwise None.

    Example:
    prompt = extract_prompt("Hey smariot, what's the weather today?", "Hey smariot")
    logger.info(prompt)  # Output: "what's the weather today?"

    Notes:
    - The `re` module must be imported for regular expression operations.
    - The function assumes that the wake word is a distinct word or phrase used to trigger the voice assistant.
    - The regular expression pattern accounts for optional whitespace and punctuation immediately following the wake word.
    """
    logger.debug("Extracting prompt from transcribed text: %s with wake word: %s", transcribed_text, wake_word)

    pattern = rf'\b{re.escape(wake_word)}[\s,.?!]*([A-Za-z0-9].*)'
    match = re.search(pattern, transcribed_text, re.IGNORECASE)

    if match:
        prompt = match.group(1).strip()
        logger.info("Extracted prompt: %s", prompt)
        return prompt
    else:
        logger.info("Wake word not found in transcribed text")
        return None
def speak(text):
    """
    Converts the given text into speech and plays it through the audio output device.

    This function uses the OpenAI client to generate speech from text, and plays the resulting audio in real-time using PyAudio.

    Parameters:
    text (str): The text to be converted into speech.

    Returns:
    None

    Example:
    speak("Hello, how can I assist you today?")
    # This will convert the text into speech and play it through the audio output device.

    Notes:
    - The `pyaudio` module must be imported and configured correctly for audio playback.
    - The `openai_client` must be defined and configured to access the OpenAI API for text-to-speech conversion.
    - The function uses the 'tts-1' model and 'echo' voice for speech synthesis.
    - The `response_format` is set to 'pcm' and the audio is streamed in chunks of 1024 bytes.
    - The function starts playing audio when it detects a non-silence chunk, determined by the `silence_threshold`.
    """
    try:
        logger.debug("Opening PyAudio stream")
        player_stream = pyaudio.PyAudio().open(format=pyaudio.paInt16, channels=1, rate=24000, output=True)
        stream_start = False

        logger.debug("Generating speech for text: %s", text)
        with openai_client.audio.speech.with_streaming_response.create(
            model='tts-1',
            voice='echo',
            response_format='pcm',
            input=text,
        ) as response:
            silence_threshold = 0.01
            for chunk in response.iter_bytes(chunk_size=1024):
                if stream_start:
                    player_stream.write(chunk)
                else:
                    if max(chunk) > silence_threshold:
                        player_stream.write(chunk)
                        stream_start = True
        logger.info("Speech playback completed")
    except Exception as e:
        logger.error("An error occurred during speech synthesis or playback: %s", e)
start_listening()
